# GoReleser config
#
# documentation at http://goreleaser.com
---
project_name: vpp-probe

build:
  id: vpp-probe-build
  dir: ../
  binary: vpp-probe
  goos:
    - linux
    - darwin
  goarch:
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
  flags:
    - -trimpath
  ldflags:
    - -s -w
    - -X go.ligato.io/vpp-probe/internal/version.version=v{{.Version}}
    - -X go.ligato.io/vpp-probe/internal/version.commit={{.FullCommit}}
    - -X go.ligato.io/vpp-probe/internal/version.branch={{.Branch}}
    - -X go.ligato.io/vpp-probe/internal/version.buildStamp={{.Timestamp}}
    - -X go.ligato.io/vpp-probe/internal/version.buildHost={{.Env.HOSTNAME}}
    - -X go.ligato.io/vpp-probe/internal/version.buildUser={{.Env.USER}}
  env:
    - CGO_ENABLED=0

archives:
  - id: vpp-probe-archive
    builds:
      - vpp-probe-build
    format: tar.gz
    wrap_in_directory: true
    files:
      - ../README.md
      - ../docs/*
    allow_different_binary_count: true
    name_template: "vpp-probe_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '!^docs:'
      - typo

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ligato/vpp-probe:{{ .Tag }}"
      - "ligato/vpp-probe:v{{ .Major }}"
      - "ligato/vpp-probe:v{{ .Major }}.{{ .Minor }}"
      - "ligato/vpp-probe:latest"
    ids:
      - vpp-probe-build
    use_buildx: true

release:
  github:
    owner: ligato
    name: vpp-probe
  ids:
    - vpp-probe-archive
  prerelease: true
  name_template: "{{.Tag}}"

